### ISSUE TITLE
Stick Tables 

### ISSUE THREAD

**Issue by alexseys** [propyless/puppet-module-haproxywrapper#8]
Hi
How would I go about adding stick tables to the config using your module?

Thank you
Alexsey

**Comment by anders-larsson** [comment]
Hi,

Looking at the code at Puppetlabs it looks like it would be configured something like this (I haven't tested it mind you). See `Set up stick-tables for a frontend (or a backend)` on [puppetlabs-haproxy](https://github.com/puppetlabs/puppetlabs-haproxy#set-up-a-resolver).
```
haproxywrapper::backend:
  'backend01':
    options:
      -
        stick-table: 'type ip size 1 nopurge peers LB'
        stick: 'on dst'
```

**Comment by alexseys** [comment]
Thank you sir. I'll post results here later.

**Comment by anders-larsson** [comment]
Hi,

How did it go? Did you get it working?

**Comment by alexseys** [comment]
I have config working but haproxy not in production yet so no much going on there.

**Comment by alexseys** [comment]
Hi,
Unfortunatelly I am not able to make this work.
Symptoms:
Configure haproxy.yml in such way:
```

haproxywrapper::frontend:
  http_in:
    bind:
      '0.0.0.0:80': ''
    mode: 'http'
    options:
      http-request: 'track-sc0 src table st_src_global'
      http-request: 'deny deny_status 429 if { sc_http_req_rate(0) gt 100 }'
      option:
...............
  https_in:
    bind:
      '0.0.0.0:443': 'ssl crt /etc/ssl/private/haproxy/' 
    mode: 'http'
    options:
      http-request: 'add-header X-Forwarded-Proto https'
      http-request: 'track-sc0 src table st_src_global'
      http-request: 'deny deny_status 429 if { sc_http_req_rate(0) gt 100 }'
      option:
        - 'http-server-close'
        - 'httplog'
      use_backend:
etc.................
haproxywrapper::backend: 
  st_src_global:
    options:
      stick-table: type ip size 1m expire 10s store http_req_rate(10s)
etc......
```

Lines are not added to config on server,  this is config i get:
```

frontend http_in
  bind 0.0.0.0:80
  mode http
  http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }
  option http-server-close
  option httplog
  use_backend .......

frontend https_in
  bind 0.0.0.0:443 ssl crt /etc/ssl/private/haproxy/
  mode http
  http-request add-header X-Forwarded-Proto https
  option http-server-close
  option httplog
  use_backend.........
```

While running puppet log shows:

```
Notice: /Stage[main]/Haproxy/Haproxy::Instance[haproxy]/Haproxy::Config[haproxy]/Concat[/etc/haproxy/haproxy.cfg]/File[/etc/haproxy/haproxy.cfg]/content:
--- /etc/haproxy/haproxy.cfg	2020-03-19 13:48:30.400033932 -0400
+++ /tmp/puppet-file20200319-87331-nssinp	2020-03-19 13:53:02.974906759 -0400
@@ -36,7 +36,6 @@
 frontend http_in
   bind 0.0.0.0:80
   mode http
-  http-request track-sc0 src table st_src_global
   http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }
   option http-server-close
   option httplog
@@ -61,8 +60,6 @@
 frontend https_in
   bind 0.0.0.0:443 ssl crt /etc/ssl/private/haproxy/
   mode http
-  http-request track-sc0 src table st_src_global
-  http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }
   http-request add-header X-Forwarded-Proto https
   option http-server-close
   option httplog

```
See how it removes lines, that I added manually to the file?
File altered manually checks out fine:

Add lines manually, check config:
```
grep http-request   /etc/haproxy/haproxy.cfg
...
  http-request track-sc0 src table st_src_global
  http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }
  http-request track-sc0 src table st_src_global
  http-request deny deny_status 429 if { sc_http_req_rate(0) gt 100 }
...
haproxy04:~# haproxy -f /etc/haproxy/haproxy.cfg -c
Configuration file is valid
```


I wander where this config gets lost in wrapper module or haproxy module?

I wish i was able to decipher all of these erb files
Please let us know if there is a hope for this 

Again thank you for all your work and help!!

**Comment by alexseys** [comment]
Also should point out that some of these are not added to backend config:
```
`
backendname:
  mode: 'http' 
    options: 
      option: 
        - 'forwardfor'
      http-response: 'set-header Strict-Transport-Security max-age=31536000;includeSubDomains;preload'
      http-response: 'set-header X-Content-Type-Options: nosniff'
      http-response: 'set-header X-XSS-Protection: 1;mode=block'
      http-response: 'set-header X-Frame-Options: DENY'
      http-response: 'set-header Referrer-Policy no-referrer-when-downgrade'
      http-request: 'set-header X-Forwarded-Port %[dst_port]'
      http-request: 'add-header X-Forwarded-Proto https if { ssl_fc }'
      http-request: 'redirect scheme https if !{ ssl_fc } '
      cookie:  'confluence insert indirect nocache'
      server:
        - ..............
`
```
What is not being set:
```
      http-request: 'set-header X-Forwarded-Port %[dst_port]'
      http-response: 'set-header Strict-Transport-Security max-age=31536000;includeSubDomains;preload'
      http-response: 'set-header X-Content-Type-Options: nosniff'
      http-response: 'set-header X-XSS-Protection: 1;mode=block'
      http-response: 'set-header X-Frame-Options: DENY'

```
Do not know if it relates to special characters or anything else, but i was not able to make it work.
I know these work or at least do not cause errors when added directly to haproxy.cfg
